=== toyvoKalevala/EPAM-Task2-XML/src/test/resources/tariffsExt.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs" elementFormDefault="qualified">
    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="tns:tariff" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="tariffs">
        <sequence>
            <element name="operatorname">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="A1"/>
                        <enumeration value="MTS"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="payroll" type="double"/>
        </sequence>
        <attribute name="id" type="tns:id" use="required"/>
        <attribute name="name" type="string"/>
    </complexType>
    <simpleType name="id">
        <restriction base="ID">
            <pattern value="(ID-)[0-9]{3}"/>
        </restriction>
    </simpleType>
    <complexType name="calltariffs">
        <complexContent>
            <extension base="tns:tariffs">
                <sequence>
                    <element name="SMSPrice" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="internettariffs">
        <complexContent>
            <extension base="tns:tariffs">
                <sequence>
                    <element name="connectionspeed" type="int"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <element name="tariff" type="tns:tariffs"/>
    <element name="calltariffs" type="tns:calltariffs" substitutionGroup="tns:tariff"/>
    <element name="internettariffs" type="tns:internettariffs" substitutionGroup="tns:tariff"/>
</schema>

=== toyvoKalevala/EPAM-Task2-XML/src/test/resources/tariffsExt.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.com/tariffs"
         xsi:schemaLocation="http://www.example.com/tariffs tariffsExt.xsd">
    <calltariffs id='ID-011' name='Light'>
        <operatorname>A1</operatorname>
        <payroll>10.00</payroll>
        <SMSPrice>0.05</SMSPrice>
    </calltariffs>
    <calltariffs id='ID-012' name='Medium'>
        <operatorname>A1</operatorname>
        <payroll>15.00</payroll>
        <SMSPrice>0.05</SMSPrice>
    </calltariffs>
    <internettariffs id='ID-021' name='Home'>
        <operatorname>A1</operatorname>
        <payroll>10.00</payroll>
        <connectionspeed>50</connectionspeed>
    </internettariffs>
    <internettariffs id='ID-022' name='Home+'>
        <operatorname>A1</operatorname>
        <payroll>15.00</payroll>
        <connectionspeed>100</connectionspeed>
    </internettariffs>
</tariffs>
